import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CV Builder App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Bienvenido a la aplicación CV Builder (Next.js)</h1>
        <p>Esta es la página principal.</p>
      </main>
    </div>
  );
}